Style/FrozenStringLiteralComment:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/MethodParameterName:
  Enabled: false
Style/EvenOdd:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
